
package com.mycompany.proyectogrupo2.util.pantallas;

import com.mycompany.proyectogrupo2.dao.ActivoDao;
import com.mycompany.proyectogrupo2.dao.UbicacionActivoDao;
import com.mycompany.proyectogrupo2.dao.impl.ActivoDaoImpl;
import com.mycompany.proyectogrupo2.dao.impl.UbicacionActivoDaoImpl;
import com.mycompany.proyectogrupo2.model.Activo;

import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaRegistrarActivo extends javax.swing.JFrame {

    private ActivoDao activoDao;
    private UbicacionActivoDao ubicacionDao;
    
    public VentanaRegistrarActivo() {
        initComponents();
        this.activoDao = new ActivoDaoImpl();
        this.ubicacionDao = new UbicacionActivoDaoImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        codigoBarrasTxt = new javax.swing.JTextField();
        valorTxt = new javax.swing.JTextField();
        estadoTxt = new javax.swing.JTextField();
        FechaMantTxt = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registrar Activo");

        Nombre.setText("Nombre:");

        jLabel2.setText("Codigo de Barras:");

        Cedula.setText("Valor (CRC):");

        jLabel3.setText("Estado:");

        jLabel4.setText("Fecha Mantenimiento:");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        codigoBarrasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasTxtActionPerformed(evt);
            }
        });

        estadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTxtActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar Activo");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(volverBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addComponent(guardarBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(nombreTxt)
                                .addComponent(valorTxt)
                                .addComponent(estadoTxt)
                                .addComponent(FechaMantTxt)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoBarrasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cedula)
                    .addComponent(valorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FechaMantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(guardarBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        String nombreActivo = nombreTxt.getText().trim();
        String codigoBarras = codigoBarrasTxt.getText().trim();
        String valorStr = valorTxt.getText().trim();
        String estado = estadoTxt.getText().trim();
        String fechaMant = FechaMantTxt.getText().trim();   
            
        if (nombreActivo.isEmpty() || codigoBarras.isEmpty() || valorStr.isEmpty() || estado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completá: Nombre activo, Código de barras, Valor y Estado.");
            return;
            }
        
        double valor;
            
            try {
            // permitimos coma o punto
            valor = Double.parseDouble(valorStr.replace(",", "."));
            if (valor < 0) {
                JOptionPane.showMessageDialog(this, "El valor no puede ser negativo.");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El valor debe ser numérico. Ej: 150000 o 150000.50");
            return;
    }//GEN-LAST:event_guardarBtnActionPerformed
     
    String fechaMantenimiento = null;
        if (!fechaMant.isEmpty()) {

            if (!fechaMant.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "La fecha debe ser YYYY-MM-DD (ej: 2025-12-20) o dejala en blanco.");
                return;
            }
            fechaMantenimiento = fechaMant;
        }
      
       try {

            Activo a = new Activo();
            a.setNombreActivo(nombreActivo);
            a.setCodigoBarras(codigoBarras);
            a.setValorActivo(valor);
            a.setEstado(estado);
            a.setFechaMantenimiento(fechaMantenimiento);

            int idActivoNuevo = activoDao.insertar(a);

            if (idActivoNuevo == -1) {
                JOptionPane.showMessageDialog(this, "Error: no se pudo registrar el activo.");
                return;
            }

            //if (!ubicacionStr.isEmpty()) {
            //    registrarUbicacionInicial(idActivoNuevo, ubicacionStr);
            //}

            JOptionPane.showMessageDialog(this, "Activo registrado exitosamente. ID: " + idActivoNuevo);

 
            nombreTxt.setText("");
            codigoBarrasTxt.setText("");
            valorTxt.setText("");
            estadoTxt.setText("");
            FechaMantTxt.setText("");

            // Volver a principal
            VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
            ventanaPrincipal.setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar activo: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    private void registrarUbicacionInicial(int idActivo, String ubicacionStr) throws Exception {
        String tipo;
        Integer idDestino = null;

        String[] partes = ubicacionStr.split(":");
        tipo = partes[0].trim();

        if (!(tipo.equalsIgnoreCase("Sucursal") || tipo.equalsIgnoreCase("Cliente") || tipo.equalsIgnoreCase("Mantenimiento"))) {
            throw new Exception("Ubicación inválida. Use: Sucursal:ID, Cliente:ID o Mantenimiento");
        }

        if (!tipo.equalsIgnoreCase("Mantenimiento")) {
            if (partes.length != 2) {
                throw new Exception("Formato de ubicación inválido. Use: Sucursal:ID o Cliente:ID");
            }
            try {
                idDestino = Integer.parseInt(partes[1].trim());
            } catch (NumberFormatException ex) {
                throw new Exception("El ID de destino debe ser numérico. Ej: Sucursal:2");
            }
        }

        Date hoy = new Date(System.currentTimeMillis());
        ubicacionDao.insertar(idActivo, capitalizar(tipo), idDestino, hoy, null);
    }

    private String capitalizar(String s) {
        s = s.toLowerCase();
        return s.substring(0, 1).toUpperCase() + s.substring(1);
    }
    
        
    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void estadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTxtActionPerformed

    private void codigoBarrasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasTxtActionPerformed
/// borre el main xq esto solo se abre cuando se hace click en el boton
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JTextField FechaMantTxt;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField codigoBarrasTxt;
    private javax.swing.JTextField estadoTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField valorTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
