/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectogrupo2.util.pantallas;

import com.mycompany.proyectogrupo2.dao.ActivoDao;
import com.mycompany.proyectogrupo2.dao.UbicacionActivoDao;
import com.mycompany.proyectogrupo2.dao.impl.ActivoDaoImpl;
import com.mycompany.proyectogrupo2.dao.impl.UbicacionActivoDaoImpl;
import com.mycompany.proyectogrupo2.model.Activo;
import com.mycompany.proyectogrupo2.model.UbicacionActivo;

import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaRevisarActivo extends javax.swing.JFrame {

    private ActivoDao activoDao;
    private UbicacionActivoDao ubicacionDao;

    public VentanaRevisarActivo() {
        initComponents();
        this.activoDao = new ActivoDaoImpl();
        this.ubicacionDao = new UbicacionActivoDaoImpl();

        jLabel1.setText("Revisar activos");
        cargarActivos();
    }
    
    private void cargarActivos() {
        try {
            List<Activo> activos = activoDao.listar();

            DefaultTableModel modelo = (DefaultTableModel) tablaActivos.getModel();
            modelo.setRowCount(0);

            for (Activo a : activos) {
                modelo.addRow(new Object[] {
                    a.getIdActivo(),
                    a.getNombreActivo(),
                    a.getCodigoBarras(),
                    a.getValorActivo(),
                    a.getEstado(),
                    a.getFechaMantenimiento()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar activos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

   private Integer getIdActivoSeleccionado() {
        int fila = tablaActivos.getSelectedRow();
        if (fila == -1) return null;

        Object val = tablaActivos.getValueAt(fila, 0); // columna 0 = ID
        if (val == null) return null;

        try {
            return Integer.parseInt(val.toString());
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private void verUltimaUbicacion() {
        Integer idActivo = getIdActivoSeleccionado();
        if (idActivo == null) {
            JOptionPane.showMessageDialog(this, "Seleccioná un activo de la tabla.");
            return;
        }

        try {
            Optional<UbicacionActivo> uOpt = ubicacionDao.ultimaPorActivo(idActivo);

            if (uOpt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Este activo no tiene ubicaciones registradas.");
                return;
            }

            UbicacionActivo u = uOpt.get();

            String destino = (u.getIdDestino() == null || u.getIdDestino().trim().isEmpty())
                    ? "N/A"
                    : u.getIdDestino();

            String msg =
                    "Activo ID: " + u.getIdActivo() + "\n" +
                    "Tipo ubicación: " + u.getTipoUbicacion() + "\n" +
                    "ID destino: " + destino + "\n" +
                    "Fecha inicio: " + u.getFechaInicio() + "\n" +
                    "Fecha fin: " + (u.getFechaFin() == null ? "N/A" : u.getFechaFin());

            JOptionPane.showMessageDialog(this, msg, "Última ubicación", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error consultando ubicación: " + ex.getMessage());
            ex.printStackTrace();
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActivos = new javax.swing.JTable();
        volverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Lista de activos");

        tablaActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ubicación", "ID destino", "Fecha Inicio", "Fecha Fin"
            }
        ));
        jScrollPane1.setViewportView(tablaActivos);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(volverBtn)
                        .addGap(197, 197, 197))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(volverBtn)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaActivos;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
