
package com.mycompany.proyectogrupo2.util.pantallas;

import com.mycompany.proyectogrupo2.dao.impl.SucursalDaoImpl;
import com.mycompany.proyectogrupo2.model.Sucursal;
import com.mycompany.proyectogrupo2.dao.SucursalDao;

import java.util.Optional;
import javax.swing.JOptionPane;

public class VentanaActualizarSucursal extends javax.swing.JFrame {
    private SucursalDao sucursalDao;
    private Sucursal sucursalActual;
    /**
     * Creates new form VentanaActualizarCliente
     */
    public VentanaActualizarSucursal() {
        initComponents();
        this.sucursalDao = new SucursalDaoImpl();
        this.sucursalActual = null;
        deshabilitarCampos();
    }
    
    private void deshabilitarCampos(){
        nombreTxt.setEnabled(false);
        direccionTxt.setEnabled(false);
        telefonoTxt.setEnabled(false);
        guardarBtn.setEnabled(false);
    }
    
    private void habilitarCampos(){
        nombreTxt.setEnabled(true);
        direccionTxt.setEnabled(true);
        telefonoTxt.setEnabled(true);
        guardarBtn.setEnabled(true);
    }
    
    private void limpiarCampos(){
        cedulaTxt.setText("");
        nombreTxt.setText("");
        direccionTxt.setText("");
        telefonoTxt.setText("");
    }
    
    private void buscarSucursal(){
        String idStr = cedulaTxt.getText().trim();
        
        if (idStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ID para buscar una sucursal!");
            return;
        }
        
        int id;
        
        try {
             id = Integer.parseInt(idStr);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"El ID debe ser un número entero");
            return;
        }
        
        try {
            Optional <Sucursal> resultado = sucursalDao.porId(id);
            
            if (resultado.isPresent()) {
                sucursalActual = resultado.get();
                
                nombreTxt.setText(sucursalActual.getNombreSucursal());
                direccionTxt.setText(sucursalActual.getDireccion());
                telefonoTxt.setText(sucursalActual.getTelefono());
                
                habilitarCampos();
                JOptionPane.showMessageDialog(this, "Sucursal encontrada. Editá los datos y guardalos.");
            }else{
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.");
                deshabilitarCampos();
                limpiarCampos();
                sucursalActual = null;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al buscar sucursal: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void guardarCambios(){
        if (nombreTxt.getText().trim().isEmpty() || nombreTxt.getText().trim().isEmpty() || direccionTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Asegurese de completar todos los espacios!");
            return;
        }
        
        String nombreSucursal = nombreTxt.getText().trim();
        String direccion = direccionTxt.getText().trim();
        String telefono = telefonoTxt.getText().trim();
        
        try {
             sucursalActual.setNombreSucursal(nombreSucursal);
             sucursalActual.setDireccion(direccion);
             sucursalActual.setTelefono(telefono);
             
             
            int resultado = sucursalDao.actualizar(sucursalActual);
            
            if (resultado > 0){
                JOptionPane.showMessageDialog(this, "Sucursal actualizada correctamente!");
                limpiarCampos();
                deshabilitarCampos();
                sucursalActual = null;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la sucursal!");
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Error al actualizar sucursal: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        volverBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        nombreTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Actualizar sucursal");

        jLabel2.setText("Buscar sucursal por ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Informacion de la sucursal");

        jLabel4.setText("Nombre:");

        jLabel7.setText("Direccion:");

        jLabel8.setText("Telefono:");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(volverBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guardarBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(direccionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                            .addComponent(nombreTxt)
                                            .addComponent(telefonoTxt))))))
                        .addGap(18, 18, 18)
                        .addComponent(buscarBtn)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscarBtn))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(guardarBtn))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        VentanaPrincipal ventanaPrincipal  = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardarCambios();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        buscarSucursal();
    }//GEN-LAST:event_buscarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
